# Generated by Django 3.1.5 on 2021-11-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfhelparticle',
            name='last_updated_by',
            field=models.CharField(default='blank', max_length=50),
            preserve_default=False,
        ),
    ]
