# Generated by Django 3.1.5 on 2021-11-12 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_application', '0002_selfhelparticle_last_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfhelparticle',
            name='created_by',
        ),
    ]
