# Generated by Django 3.1.5 on 2021-11-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_application', '0003_remove_selfhelparticle_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfhelparticle',
            name='description',
            field=models.CharField(default='default', max_length=800),
            preserve_default=False,
        ),
    ]
