# Generated by Django 3.1.5 on 2021-12-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_application', '0004_selfhelparticle_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='selfhelparticle',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
