# Generated by Django 3.1.5 on 2021-12-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_application', '0005_auto_20211202_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfhelparticle',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/'),
        ),
    ]
