# Generated by Django 3.1.5 on 2021-12-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_application', '0007_auto_20211208_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfhelparticle',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images'),
        ),
    ]
