# Generated by Django 3.1.5 on 2021-12-09 06:57

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_application', '0009_auto_20211208_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfhelparticle',
            name='article_image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/article_media'), upload_to=''),
        ),
    ]
