# Generated by Django 3.1.5 on 2021-12-09 07:04

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_application', '0010_auto_20211208_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfhelparticle',
            name='article_image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:/My Coding Projects/Toray_Project/Toray_Catalog/article_media'), upload_to=''),
        ),
    ]
